### PR TITLE
Fix sourcemap for files in subdirectories

### PR DESCRIPTION
**Pull request by zsapozhnikov**
I've ran into the problem:
My entry is in subdirectory and `stats.compilation.assets` have the keys like `upload/uploader.2f661975.js` and `upload/uploader.2f661975.js.map`. Js file has the relative link to sourcemap `#sourceMappingURL=uploader.2f661975.js.map`. So it won't be founded in `assets` object
https://github.com/1stdibs/new-relic-source-map-webpack-plugin/blob/db4a293d0f210503d4fcd0e42a17104add98f477/src/uploadSourceMap.js#L23
because it tries to find `uploader.2f661975.js.map` instead of `upload/uploader.2f661975.js.map`. This PR fixes that. 

Another idea was to check map file existence, but I think it's not a good idea to load filesystem every check

### CODE REVIEW

**Comment by zsapozhnikov** [comment]
@twhid @robrichard guys, please, take a look)

**Comment by zsapozhnikov** [comment]
ping @twhid

**Comment by zsapozhnikov** [comment]
@robrichard can you merge and create tag, please? @twhid is anavailable

**Comment by twhid** [comment]
@kostasmanionis can you or @niqqq25 take this?

Thanks!

**Comment by niqqq25** [comment]
@zsapozhnikov After many tries, I still haven't managed to replicate the same behaviour. It would be helpful if you could share with us yours webpack config file.

**Comment by zsapozhnikov** [comment]
```json
{
  "context": "/var/www",
  "entry": {
    "uploader/uploader/calendar": "/var/www/assets/themes/base/uploader/uploader/calendar.js"
  },
  "mode": "development",
  "output": {
    "path": "/var/www/public/dist/some_dir",
    "filename": "[name].js",
    "publicPath": "//onp.test/dist/some_dir/",
    "pathinfo": true
  },
  "module": {
    "rules": [
      {
        "test": {},
        "exclude": {},
        "use": [
          {
            "loader": "babel-loader",
            "options": {
              "cacheDirectory": true,
              "sourceType": "unambiguous",
              "presets": [
                [
                  "@babel/preset-env",
                  {
                    "modules": false,
                    "targets": {},
                    "forceAllTransforms": false,
                    "useBuiltIns": false,
                    "corejs": null
                  }
                ]
              ],
              "plugins": [
                "@babel/plugin-syntax-dynamic-import"
              ]
            }
          }
        ]
      },
      {
        "resolve": {
          "mainFields": [
            "style",
            "main"
          ],
          "extensions": [
            ".css"
          ]
        },
        "test": {},
        "oneOf": [
          {
            "resourceQuery": {},
            "use": [
              "/var/www/node_modules/mini-css-extract-plugin/dist/loader.js",
              {
                "loader": "css-loader",
                "options": {
                  "sourceMap": true,
                  "importLoaders": 0,
                  "modules": true,
                  "localIdentName": "[local]_[hash:base64:5]"
                }
              }
            ]
          },
          {
            "use": [
              "/var/www/node_modules/mini-css-extract-plugin/dist/loader.js",
              {
                "loader": "css-loader",
                "options": {
                  "sourceMap": true,
                  "importLoaders": 0,
                  "modules": false,
                  "localIdentName": "[local]_[hash:base64:5]"
                }
              }
            ]
          }
        ]
      },
      {
        "test": {},
        "loader": "file-loader",
        "options": {
          "name": "images/[name].[hash:8].[ext]",
          "publicPath": "//onp.test/dist/some_dir/"
        }
      },
      {
        "test": {},
        "loader": "file-loader",
        "options": {
          "name": "fonts/[name].[hash:8].[ext]",
          "publicPath": "//onp.test/dist/some_dir/"
        }
      },
      {
        "test": {},
        "oneOf": [
          {
            "resourceQuery": {},
            "use": [
              "/var/www/node_modules/mini-css-extract-plugin/dist/loader.js",
              {
                "loader": "css-loader",
                "options": {
                  "sourceMap": true,
                  "importLoaders": 0,
                  "modules": true,
                  "localIdentName": "[local]_[hash:base64:5]"
                }
              },
              {
                "loader": "less-loader",
                "options": {
                  "sourceMap": true
                }
              }
            ]
          },
          {
            "use": [
              "/var/www/node_modules/mini-css-extract-plugin/dist/loader.js",
              {
                "loader": "css-loader",
                "options": {
                  "sourceMap": true,
                  "importLoaders": 0,
                  "modules": false,
                  "localIdentName": "[local]_[hash:base64:5]"
                }
              },
              {
                "loader": "less-loader",
                "options": {
                  "sourceMap": true
                }
              }
            ]
          }
        ]
      },
      {
        "use": [
          "cache-loader"
        ]
      }
    ]
  },
  "plugins": [
    {
      "options": {
        "filename": "[name].css",
        "chunkFilename": "[name].css"
      }
    },
    {
      "entriesToDelete": []
    },
    {
      "opts": {
        "publicPath": null,
        "basePath": "dist/some_dir/",
        "fileName": "manifest.json",
        "transformExtensions": {},
        "writeToFileEmit": true,
        "seed": {},
        "map": null,
        "generate": null,
        "sort": null
      }
    },
    {
      "definitions": {
        "$": "jquery",
        "jQuery": "jquery",
        "window.jQuery": "jquery"
      }
    },
    {
      "paths": [
        "**/*"
      ],
      "options": {
        "root": "/var/www/public/dist/some_dir",
        "verbose": false,
        "allowExternal": false,
        "dry": false
      }
    },
    {
      "definitions": {
        "process.env": {
          "NODE_ENV": "\"development\""
        }
      }
    },
    {
      "compilationSuccessInfo": {
        "messages": []
      },
      "shouldClearConsole": false,
      "formatters": [
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "transformers": [
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "outputPath": "public/dist/some_dir",
      "friendlyErrorsPlugin": {
        "compilationSuccessInfo": {
          "messages": []
        },
        "shouldClearConsole": false,
        "formatters": [
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "transformers": [
          null,
          null,
          null,
          null,
          null,
          null
        ]
      }
    },
    {
      "resourceRegExp": {}
    },
    {
      "options": {
        "filename": "entrypoints.json",
        "prettyPrint": false,
        "update": false,
        "fullPath": true,
        "manifestFirst": true,
        "useCompilerPath": false,
        "fileTypes": [
          "js",
          "css"
        ],
        "includeAllFileTypes": true,
        "keepInMemory": false,
        "integrity": false,
        "path": "/var/www/public/dist/some_dir",
        "entrypoints": true
      }
    }
  ],
  "optimization": {
    "namedModules": true,
    "chunkIds": "named",
    "runtimeChunk": "single",
    "splitChunks": {
      "chunks": "all",
      "cacheGroups": {
        "coreVendor": {
          "name": "coreVendor",
          "priority": 10,
          "enforce": true
        },
        "jqueryUi": {
          "name": "jqueryUi",
          "priority": 9,
          "enforce": true
        },
        "legacyBaseStyles": {
          "name": "legacyBaseStyles",
          "test": {},
          "priority": 7,
          "enforce": true
        },
        "legacyBaseMobileStyles": {
          "name": "legacyBaseMobileStyles",
          "test": {},
          "priority": 7,
          "enforce": true
        },
        "legacyCoreLibStyles": {
          "name": "legacyCoreLibStyles",
          "test": {},
          "priority": 9,
          "enforce": true
        }
      }
    }
  },
  "watchOptions": {
    "ignored": {}
  },
  "devtool": "inline-source-map",
  "performance": {
    "hints": false
  },
  "stats": {
    "hash": false,
    "version": false,
    "timings": false,
    "assets": false,
    "chunks": false,
    "maxModules": 0,
    "modules": false,
    "reasons": false,
    "children": false,
    "source": false,
    "errors": false,
    "errorDetails": false,
    "warnings": false,
    "publicPath": false,
    "builtAt": false
  },
  "resolve": {
    "extensions": [
      ".wasm",
      ".mjs",
      ".js",
      ".json",
      ".jsx",
      ".vue",
      ".ts",
      ".tsx"
    ],
    "alias": {
    }
  },
  "externals": []
}
```

the result structure is
https://i.imgur.com/aptikbN.png

**Comment by niqqq25** [comment]
@zsapozhnikov I don't understand how can you have two different files: `upload/uploader.2f661975.js and upload/uploader.2f661975.js.map` if you are using `"devtool": "inline-source-map"`?

**Comment by zsapozhnikov** [comment]
@niqqq25 sorry, it was dev build, I've fixed my comment

**Comment by niqqq25** [comment]
@zsapozhnikov The problem is caused by this line:
 ` "entry": {
    "uploader/uploader/calendar": "/var/www/assets/themes/base/uploader/uploader/calendar.js"
  }`.
You should name the entry `calendar` instead of `uploader/uploader/calendar`. Or is there a particular reason why did you name it like this?

**Comment by zsapozhnikov** [comment]
@niqqq25 I don't see any information in webpack docs that I `should` do that. This is a valid representation of entry name, I have more than 180 entries and they are grouped like that. As an example I have `account/profile/edit` and `account/profile/show` and I like that their names are paths to the directories they are in. But it's a matter of taste of course. So, I don't see any reason why valid string can't be an entry key

**Comment by robrichard** [comment]
agreed that `uploader/uploader/calendar` is a valid entry name

**Comment by zsapozhnikov** [comment]
So, any other questions or comments? Or we can merge this?)

**Comment by kostasmanionis** [comment]
We're working on a slightly different way of detecting sourcemaps, we think it's gonna solve this problem. We'll give you a release candidate version to try out and see if it works. Expect it tomorrow.

**Comment by zsapozhnikov** [comment]
@kostasmanionis ok

**Comment by kostasmanionis** [comment]
@zsapozhnikov published a new version, could you give `1.2.0-rc.1` a try? Let us know how it goes.

**Comment by zsapozhnikov** [comment]
@kostasmanionis sourcemap for entry is uploaded now, but for chunks there are no sourcemaps
Before:
```
Entrypoint uploader/uploader/two_sided [big] = runtime.90eb8a53.js runtime.90eb8a53.js.map coreVendor.d4886563.js coreVendor.d4886563.js.map legacyCoreLibStyles.edc7a711.css legacyCoreLibStyles.90c957a9.js legacyCoreLibStyles.90c957a9.js.map jqueryUi.8ec86088.js jqueryUi.8ec86088.js.map legacyBaseStyles.93736635.css legacyBaseStyles.739fba54.js legacyBaseStyles.739fba54.js.map uploader/uploader/two_sided.e85d0ec4.css uploader/uploader/two_sided.f850a31f.js uploader/uploader/two_sided.f850a31f.js.map
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/0.aaf5fed3.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/1.ef0ae25c.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/2.d20a8eda.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/3.7b4ac08d.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/4.79a95f65.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/coreVendor.d4886563.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/jqueryUi.8ec86088.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/legacyBaseStyles.739fba54.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/legacyCoreLibStyles.90c957a9.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/runtime.90eb8a53.js uploaded to newrelic
sourceMap for undefined uploaded to newrelic
```

After:
```
Entrypoint uploader/uploader/two_sided [big] = runtime.8afbc986.js runtime.8afbc986.js.map coreVendor.d4886563.js coreVendor.d4886563.js.map legacyCoreLibStyles.7696d131.css legacyCoreLibStyles.90c957a9.js legacyCoreLibStyles.90c957a9.js.map jqueryUi.8ec86088.js jqueryUi.8ec86088.js.map legacyBaseStyles.93736635.css legacyBaseStyles.739fba54.js legacyBaseStyles.739fba54.js.map uploader/uploader/two_sided.e85d0ec4.css uploader/uploader/two_sided.f850a31f.js uploader/uploader/two_sided.f850a31f.js.map
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/coreVendor.d4886563.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/jqueryUi.8ec86088.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/legacyBaseStyles.739fba54.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/legacyCoreLibStyles.90c957a9.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/runtime.90eb8a53.js uploaded to newrelic
sourceMap for https://assets1.onpstatic.com/dist/OvernightPrints/uploader/uploader/two_sided.f850a31f.js uploaded to newrelic
```

**Comment by kostasmanionis** [comment]
Right, forgot that async chunks are a bit special... Let's try this one more time with `1.2.0-rc.2`

**Comment by zsapozhnikov** [comment]
yeah, now everything is ok

**Comment by kostasmanionis** [comment]
Published `v1.2.0`, thanks for your help @zsapozhnikov! Any more issues - let us know 👍

**Comment by zsapozhnikov** [comment]
You are welcome)

**Pull request closed without merging**
