### PR TITLE
Add releaseName and releaseId as options

### PR DESCRIPTION
**Pull request by dpwilhelmsen**
This pull request add the ability to submit a release name and release id for the source maps. New Relic uses this information to properly associate errors to their code location.

### CODE REVIEW

**Comment by joshgillies** [comment]
Nice! @1stdibs any reason we haven't pulled this in yet?

**Comment by karmajunkie** [comment]
+1, would really like to see this feature added.

**Comment by tedpennings** [comment]
👍 yes please!

**Comment by twhid** [comment]
Sorry everyone, didn't realize we had gotten a PR -- d'oh!

**Pull request merged**
